version: "3.9"

services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    hostname: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"

  postgres:
    image: postgres
    hostname: ${POSTGRES_HOST}
    # networks:
    #   - appeals_app
    restart: always
    volumes:
      - ./psdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    ports:
      - "5435:5432"

  rabbit:
    image: rabbitmq:3-management-alpine
    hostname: ${RABBIT_HOST}
    # networks:
    #   - appeals_app
    restart: always
    env_file:
      - .env
    ports:
      - "${RABBIT_PORT}:5672"
      - "${RABBIT_MANAGMENT_PLUGIN_PORT}:15672"

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    restart: always
    # networks:
    #   - appeals_app
    volumes:
      - ./api:/api
    env_file:
      - .env
    ports:
      - "8888:8888"
    depends_on:
      - rabbit
      - postgres
    links:
      - rabbit
      - postgres

  appeals_writer:
    build:
      context: .
      dockerfile: ./appeals_writer/Dockerfile
    restart: always
    # networks:
    #   - appeals_app
    volumes:
      - ./appeals_writer:/appeals_writer
    env_file:
      - .env
    ports:
      - "${APPEALS_WRITER_PORT}:8000"
    depends_on:
      - rabbit
    links:
      - rabbit

# networks:
#   appeals_app:
#     driver: bridge
