name: Appeals-writer
on:
  push:
    branches:
      - master
    paths:
      - appeals_writer/**
      - common/**
      - .github/workflows/docker-appeals-writer-image-push.yml
jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: zhigarink/appeals-registration

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./api/Dockerfile
          push: true
          tags: writer, latest, ${{ github.run_number }}
          labels: ${{ steps.meta.outputs.labels }}